In [7]:
import numpy as np

# array

In [76]:
a=np.array([1.,2.,3.])
a

array([ 1.,  2.,  3.])

# index

In [77]:
a[0]

1.0

In [78]:
a[1]

2.0

In [79]:
a[2]

3.0

* indexing produces copies

In [80]:
a1=a[1]
a1

2.0

In [81]:
a[1]+=10
print(a[1])
print(a1)

12.0
2.0


# slice

In [83]:
b=a[1:3]
b

array([ 12.,   3.])

* slicing produces views

In [85]:
for i in range(3):
    a[i]+=10
print(a)
print(b)

[ 11.  22.  13.]
[ 22.  13.]


* contrast with lists

In [262]:
l1=[1,2,3]
l1

[1, 2, 3]

In [263]:
l2=l1[1:3]
l2

[2, 3]

In [264]:
for i in range(3):
    l1[i]+=10
print(l1)
print(l2)

[11, 12, 13]
[2, 3]


* equivalent list structure

In [86]:
l1=[[1],[2],[3]]
l2=l1[1:3] #slicing lists produces a shallow copy
for i in range(3):
    l1[i][0]+=10
print(l1)
print(l2)

[[11], [12], [13]]
[[12], [13]]


# operações elemento-a-elemento

In [8]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [10]:
a+1

array([2, 3, 4])

In [11]:
a*2

array([2, 4, 6])

In [12]:
a+b

array([5, 7, 9])

In [13]:
a*b

array([ 4, 10, 18])

In [14]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001])